development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: accounts_manager_development
  pool: 5
  username: yovan
  password: "ab6307sn"
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: accounts_manager_test
  pool: 5
  username: yovan
  password: "ab6307sn"
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: accounts_manager_production
  pool: 5
  username: yovan
  password: "ab6307sn"
  host: localhost
