source 'http://rubygems.org'

gem 'rails', '3.2.16'

gem "mysql2", "0.3.11", :platforms => [:mri, :mingw]
gem "activerecord-jdbcmysql-adapter", :platforms => :jruby

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem "jquery-rails", "~> 2.0.2"

group :development do
  gem "rspec-rails", "~> 2.8"
  gem 'annotate'
end

group :test do
  gem "rspec", "~> 2.8"
end